// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvAJCnLAYUdakIfBQBLi1JxunreYJtvdI',
    appId: '1:224596807425:web:ac5fb86748192579e25500',
    messagingSenderId: '224596807425',
    projectId: 'chat-app-613f5',
    authDomain: 'chat-app-613f5.firebaseapp.com',
    storageBucket: 'chat-app-613f5.appspot.com',
    measurementId: 'G-XXKPWQHVK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHRAggIzZbsjL4qCHRGvlKrKJmGYUKC0E',
    appId: '1:224596807425:android:aea71babd6cc2f04e25500',
    messagingSenderId: '224596807425',
    projectId: 'chat-app-613f5',
    storageBucket: 'chat-app-613f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6MUkP8pWH3F_TQPTA4AYZmVgfI4UmljM',
    appId: '1:224596807425:ios:50850e1c90133818e25500',
    messagingSenderId: '224596807425',
    projectId: 'chat-app-613f5',
    storageBucket: 'chat-app-613f5.appspot.com',
    iosClientId: '224596807425-4t2bj33vk78dnre1r04m6qmrh6990ilj.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6MUkP8pWH3F_TQPTA4AYZmVgfI4UmljM',
    appId: '1:224596807425:ios:d4a71f0fb18dd193e25500',
    messagingSenderId: '224596807425',
    projectId: 'chat-app-613f5',
    storageBucket: 'chat-app-613f5.appspot.com',
    iosClientId: '224596807425-4g1ijm6ia2rhmqo08mbei827ngn4fmvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
